from django.urls import path, include
from .views import *

urlpatterns = [
    path('', home_views, name='home'),
    path('about/', about_views, name='about'),
    path('about/contacts/', contacts_views, name='contacts'),
    path('about/location/', location_views, name='location'),
    path('products/', products_views, name='products'),
    path('cart/', cart_views, name='cart'),
    path('cart/add/<str:product_type>/<int:pk>/', cart_add_views, name='cart_add'),
    path('cart/remove/<str:product_type>/<int:pk>/', cart_remove_views, name='cart_remove'),
    path('cart/checkout/', cart_checkout_views, name='cart_checkout'),
    path('delivery/', delivery_views, name='delivery'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('baking/', BakingListView.as_view(), name='baking_list'),
    path('baking/create/', BakingCreateView.as_view(), name='baking_create'),
    path('baking/<int:pk>/', BakingDetailView.as_view(), name='baking_detail'),
    path('baking/<int:pk>/update/', BakingUpdateView.as_view(), name='baking_update'),
    path('baking/<int:pk>/delete/', BakingDeleteView.as_view(), name='baking_delete'),
    path('drinks/', DrinkListView.as_view(), name='drink_list'),
    path('drinks/create/', DrinkCreateView.as_view(), name='drink_create'),
    path('drinks/<int:pk>/', DrinkDetailView.as_view(), name='drink_detail'),
    path('drinks/<int:pk>/update/', DrinkUpdateView.as_view(), name='drink_update'),
    path('drinks/<int:pk>/delete/', DrinkDeleteView.as_view(), name='drink_delete'),
    path('reviews/', ReviewListView.as_view(), name='review_list'),
    path('reviews/create/', ReviewCreateView.as_view(), name='review_create'),
    path('reviews/<int:pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('reviews/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/create/', order_create_views, name='order_create'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('profiles/', ProfileListView.as_view(), name='profile_list'),
    path('profiles/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('promotions/', PromotionListView.as_view(), name='promotion_list'),
    path('promotions/<int:pk>/', PromotionDetailView.as_view(), name='promotion_detail'),
]
