# Generated by Django 5.2.15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothes',
            new_name='Baking',
        ),
        migrations.AlterModelOptions(
            name='baking',
            options={'verbose_name': 'Выпечка', 'verbose_name_plural': 'Выпечка'},
        ),
    ]
