# Generated by Django 5.2.15 on 2026-06-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0002_rename_clothes_baking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baking',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='baking',
            name='color',
        ),
        migrations.RemoveField(
            model_name='baking',
            name='size',
        ),
        migrations.AddField(
            model_name='baking',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Диаметр (см)'),
        ),
        migrations.AddField(
            model_name='baking',
            name='filling',
            field=models.CharField(default='', max_length=255, verbose_name='Начинка'),
        ),
        migrations.AddField(
            model_name='baking',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
