# Generated by Django 5.2.15 on 2026-06-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0006_orderitem_alter_order'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='delivery',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='bakery_app.delivery',
                        verbose_name='Зона доставки',
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='bakery_app.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='review',
            name='baking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bakery_app.baking', verbose_name='Выпечка'),
        ),
        migrations.AddField(
            model_name='review',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bakery_app.drink', verbose_name='Напиток'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления на сайт'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
